AddTextEntry("WEAPON_AK47", "AK-47")
AddTextEntry("WEAPON_AR15", "AR-15")
AddTextEntry("WEAPON_DE", "Desert Eagle")
AddTextEntry("WEAPON_FNX45", "FN FNX45")
AddTextEntry("WEAPON_HUNTINGRIFLE", "Hunting Rifle")
AddTextEntry("WEAPON_M4", "M4")
AddTextEntry("WEAPON_M9", "M9A3")
AddTextEntry("WEAPON_M70", "M70")
AddTextEntry("WEAPON_M1911", "M1911")
AddTextEntry("WEAPON_MAC10", "MAC-10")
AddTextEntry("WEAPON_MK14", "MK14")
AddTextEntry("WEAPON_MOSSBERG", "Mossberg 500")
AddTextEntry("WEAPON_REMINGTON", "Remington 870")
AddTextEntry("WEAPON_SCARH", "SCAR-H")
AddTextEntry("WEAPON_SHIV", "Shiv")
AddTextEntry("WEAPON_KATANA", "Katana")
AddTextEntry("WEAPON_UZI", "UZI")
AddTextEntry("WEAPON_SLEDGEHAMMER", "Sledge Hammer")
AddTextEntry("WEAPON_MP9", "MP9")
AddTextEntry("WEAPON_HK416", "HK-416")
AddTextEntry("WEAPON_MP5", "MP5")
AddTextEntry("WEAPON_AK74", "AK-74")
AddTextEntry("WEAPON_AKS74", "AKS74-U")
AddTextEntry("WEAPON_COLBATON", "colbaton")
AddTextEntry("WEAPON_GLOCK18C", "Glock18c")
AddTextEntry("WEAPON_GLOCK22", "GLOCK-22")
AddTextEntry("WEAPON_PERFORATOR", "The Perforator")
AddTextEntry("WEAPON_BAYONETKNIFE", "Bayonet")
AddTextEntry("WEAPON_BLUEBFKNIFE", "Blue Steel Butterfly Knife")
AddTextEntry("WEAPON_BFKNIFE", "Vanilla Butterfly Knife")
AddTextEntry("WEAPON_CHBFKNIFE", "Case Hardened Butterfly Knife")
AddTextEntry("WEAPON_CRIMSONBFKNIFE", "Crimson Butterfly Knife")
AddTextEntry("WEAPON_FADEBFKNIFE", "Fade Butterfly Knife")
AddTextEntry("WEAPON_FLIPKNIFE", "Flip Knife")
AddTextEntry("WEAPON_FORESTBFKNIFE", "Forest Butterfly Knife")
AddTextEntry("WEAPON_GUTKNIFE", "Gut Knife")
AddTextEntry("WEAPON_HUNTSMANKNIFE", "Huntsman Knife")
AddTextEntry("WEAPON_KARAMBITKNIFE", "Karambit Knife")
AddTextEntry("WEAPON_SAFARIBFKNIFE", "Safari Mesh Butterfly Knife")
AddTextEntry("WEAPON_SCORCHEDBFKNIFE", "Scorched Butterfly Knife")
AddTextEntry("WEAPON_SLAUGHTERBFKNIFE", "Slaughter Butterfly Knife")
AddTextEntry("WEAPON_STAINEDRBFKNIFE", "Stained Butterfly Knife")
AddTextEntry("WEAPON_URBANRBFKNIFE", "Urban Masked Butterfly Knife")