AddTextEntry("WEAPON_AK47", "AK-47")
AddTextEntry("WEAPON_AR15", "AR-15")
AddTextEntry("WEAPON_DE", "Desert Eagle")
AddTextEntry("WEAPON_FNX45", "FN FNX45")
AddTextEntry("WEAPON_GLOCK17", "Glock17")
AddTextEntry("WEAPON_HUNTINGRIFLE", "Hunting Rifle")
AddTextEntry("WEAPON_M4", "M4")
AddTextEntry("WEAPON_M9", "M9A3")
AddTextEntry("WEAPON_M70", "M70")
AddTextEntry("WEAPON_M1911", "M1911")
AddTextEntry("WEAPON_MAC10", "MAC-10")
AddTextEntry("WEAPON_MK14", "MK14")
AddTextEntry("WEAPON_MOSSBERG", "Mossberg 500")
AddTextEntry("WEAPON_REMINGTON", "Remington 870")
AddTextEntry("WEAPON_SCARH", "SCAR-H")
AddTextEntry("WEAPON_SHIV", "Shiv")
AddTextEntry("WEAPON_UZI", "UZI")